import { Router } from 'express';
import authRoutes from './auth.routes.js';
import mediaRoutes from './media.routes.js';
import categoryRoutes from './category.routes.js';
import productRoutes from './product.routes.js';
import storeRoutes from './store.routes.js';
import cartRoutes from './cart.routes.js';
import checkoutRoutes from './checkout.routes.js';
import orderRoutes from './order.routes.js';
import paymentRoutes from './payment.routes.js';
import dashboardRoutes from './dashboard.routes.js';
import adminDashboardRoutes from './adminDashboard.routes.js';
import reviewRoutes from './review.routes.js';
import wishlistRoutes from './wishlist.routes.js';
import couponRoutes from './coupon.routes.js';
import customOrderRoutes from './customOrder.routes.js';
import notificationRoutes from './notification.routes.js';
import payoutRoutes from './payout.routes.js';
import returnRoutes from './return.routes.js';
import storeKYCRoutes from './storeKYC.routes.js';
import { listProductReviews } from '../controllers/review.controller.js';
import { listReviewQuerySchema } from '../validators/review.validator.js';
import { validateQuery } from '../validators/validator.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/media', mediaRoutes);
router.use('/categories', categoryRoutes);
router.get('/products/:productId/reviews', validateQuery(listReviewQuerySchema), listProductReviews);
router.use('/products', productRoutes);
router.use('/stores', storeRoutes);
router.use('/cart', cartRoutes);
router.use('/checkout', checkoutRoutes);
router.use('/orders', orderRoutes);
router.use('/payments', paymentRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/admin/dashboard', adminDashboardRoutes);
router.use('/reviews', reviewRoutes);
router.use('/wishlist', wishlistRoutes);
router.use('/coupons', couponRoutes);
router.use('/custom-orders', customOrderRoutes);
router.use('/notifications', notificationRoutes);
router.use('/payouts', payoutRoutes);
router.use('/returns', returnRoutes);
router.use('/kyc', storeKYCRoutes);

export default router;
